### ISSUE TITLE
Go linting struct as undeclared name from the same package

### ISSUE THREAD

**Issue by marcustut** [Nguyen-Hoang-Nam/nvim-dotfiles-kitty#12]
First, I have to thank you for your amazing work these configs and I'm not complaining, just to clarify and see whether this issue is something that can be solved 

![image](https://user-images.githubusercontent.com/59773847/136883354-df6128c4-1866-4f5e-943c-1bf91e74380f.png)

I'm having this issue where structs from the same package is identified as `undeclared name` by the linter. However, if I use `<leader>d` the LSP does navigate me to the correct file.

![image](https://user-images.githubusercontent.com/59773847/136883580-d6bb4e87-741b-4eed-b740-e5ec56f3e1b3.png)

**Comment by Nguyen-Hoang-Nam** [comment]
I just fix ^I this morning, I do not have linter for Rust in my config so this error may come from Rust Analyer.

**Comment by marcustut** [comment]
I see, I'll try disabling Rust Analyzer and see if it fixed the issue later

**Comment by Nguyen-Hoang-Nam** [comment]
Sorry, I miss your question, I think you code rust :v

**Comment by Nguyen-Hoang-Nam** [comment]
I try your repository and it show something like this.

![go](https://user-images.githubusercontent.com/74345759/136888883-2f4b4142-e6b8-4c4c-ac68-d71a21473a5e.jpg)

**Comment by Nguyen-Hoang-Nam** [comment]
@marcustut I found that [Static check](https://staticcheck.io/docs) cause this issue. You can comment lintCommand in ```lua/languages/go.lua```

```lua

M.efm = {
    {
        formatCommand = 'goimports',
        formatStdin = true,
    },
    {
        formatCommand = 'gofumpt',
        formatStdin = true,
    },
    -- {
    --     lintCommand = 'staticcheck ${INPUT}',
    --     lintFormats = {
    --         '%f:%l:%c: %m',
    --     },
    -- },
}

```

![go](https://user-images.githubusercontent.com/74345759/137122724-c2b1e744-a4d7-43b6-9480-42f11808ac85.jpg)
